apiVersion: v2
name: apatora
description: A Helm chart for apatora
type: application
version: 0.1.1
appVersion: 1.0.0

dependencies:
- name: mongodb
  version: 14.7.2
  repository: oci://registry-1.docker.io/bitnamicharts
- name: redis
  version: 18.4.0
  repository: oci://registry-1.docker.io/bitnamicharts
