---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: helm-apatora-ingress
  namespace: apatora
spec:
  ingressClassName: nginx
  rules:
  - host: apatora.k8s.localhost
    http:
      paths:
      - backend:
          service:
            name: helm-apatora
            port:
              number: 80
        path: /
        pathType: Prefix
  # tls:
  # - hosts:
  #   - argocd.k8s.localhost
  #   secretName: tls-secret

# {{- if .Values.ingress.enabled -}}
# {{- $fullName := include "apatora.fullname" . -}}
# {{- $svcPort := .Values.service.port -}}
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: {{ $fullName }}
#   labels:
#     {{- include "apatora.labels" . | nindent 4 }}
#   {{- with .Values.ingress.annotations }}
#   annotations:
#     {{- toYaml . | nindent 4 }}
#   {{- end }}
# spec:
# {{- if .Values.ingress.tls }}
#   tls:
#   {{- range .Values.ingress.tls }}
#     - hosts:
#       {{- range .hosts }}
#         - {{ . | quote }}
#       {{- end }}
#       secretName: {{ .secretName }}
#   {{- end }}
# {{- end }}
#   rules:
#   {{- range .Values.ingress.hosts }}
#     - host: {{ .host | quote }}
#       http:
#         paths:
#         {{- range .paths }}
#           - path: {{ . }}
#             backend:
#               service:
#                 name: {{ $fullName }}
#                 port:
#                   number: {{ $svcPort }}
#             path: /
#             pathType: Prefix
#         {{- end }}
#   {{- end }}
# {{- end }}
