{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "apatora.serviceAccountName" . }}
  labels:
{{ include "apatora.labels" . | nindent 4 }}
{{- end -}}
