apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-apatora
  # finalizers:
  #   - resources-finalizer.argocd.argoproj.io
spec:
  project: apps
  source:
    repoURL: 'https://github.com/Kr1Kr1/gitops.git'
    path: apps/helm-apatora
    targetRevision: main
  destination:
    namespace: apatora
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
    - Validate=true
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    - ApplyOutOfSyncOnly=false
    - Prune=true
    retry:
      limit: -1
      backoff:
        duration: 20s
        factor: 2
        maxDuration: 15m
